{
 "title": "Starlink stats",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "influxdb" }
  ]
 },
 "panels": [
  {
   "title": "Throughputs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "alias": "Max downlink",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "spacex.starlink.user_terminal.status",
     "select": [
      [
       { "params": [ "downlink_throughput_bps" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    },
    {
     "alias": "Max uplink",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "spacex.starlink.user_terminal.status",
     "select": [
      [
       { "params": [ "uplink_throughput_bps" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Ping",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "alias": "Max ping latency",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "spacex.starlink.user_terminal.status",
     "select": [
      [
       { "params": [ "pop_ping_latency_ms" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    },
    {
     "alias": "Max ping drop rate",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "spacex.starlink.user_terminal.status",
     "query": "SELECT max(\"pop_ping_drop_rate\") FROM \"spacex.starlink.user_terminal.status\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "pop_ping_drop_rate" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Drop rate",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "alias": "Alerts count",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "spacex.starlink.user_terminal.status",
     "select": [
      [
       { "params": [ "alerts" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "obstrustion rate",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "spacex.starlink.user_terminal.status",
     "select": [
      [
       { "params": [ "fraction_obstructed" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Throughputs",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "alias": "Downlink",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "spacex.starlink.user_terminal.status",
     "query": "SELECT mean(\"downlink_throughput_bps\")  * (-1) FROM \"spacex.starlink.user_terminal.status\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "downlink_throughput_bps" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Uplink",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "spacex.starlink.user_terminal.status",
     "query": "SELECT mean(\"uplink_throughput_bps\")  / 100 FROM \"spacex.starlink.user_terminal.status\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "uplink_throughput_bps" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " * (-1)" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Ping",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "alias": "Ping",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "spacex.starlink.user_terminal.status",
     "select": [
      [
       { "params": [ "pop_ping_latency_ms" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Drop rate",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "spacex.starlink.user_terminal.status",
     "query": "SELECT max(\"pop_ping_drop_rate\") FROM \"spacex.starlink.user_terminal.status\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "pop_ping_drop_rate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Drop rate",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "alias": "alerts count",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "spacex.starlink.user_terminal.status",
     "select": [
      [
       { "params": [ "alerts" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "obstrustion rate",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "spacex.starlink.user_terminal.status",
     "select": [
      [
       { "params": [ "fraction_obstructed" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Version",
   "type": "state-timeline",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "alias": "hardware_version",
     "measurement": "spacex.starlink.user_terminal.status",
     "query": "SELECT \"hardware_version\" FROM \"spacex.starlink.user_terminal.status\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "hardware_version" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "software_version",
     "measurement": "spacex.starlink.user_terminal.status",
     "query": "SELECT \"software_version\" FROM \"spacex.starlink.user_terminal.status\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "software_version" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Alerts",
   "type": "state-timeline",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "alias": "alert_install_pending",
     "measurement": "spacex.starlink.user_terminal.status",
     "query": "SELECT \"alert_install_pending\" FROM \"spacex.starlink.user_terminal.status\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "alert_install_pending" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "alert_dbf_telem_stale",
     "measurement": "spacex.starlink.user_terminal.status",
     "query": "SELECT \"alert_dbf_telem_stale\" FROM \"spacex.starlink.user_terminal.status\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "alert_dbf_telem_stale" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "alert_is_heating",
     "measurement": "spacex.starlink.user_terminal.status",
     "query": "SELECT \"alert_is_heating\" FROM \"spacex.starlink.user_terminal.status\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "alert_is_heating" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "alert_is_power_save_idle",
     "measurement": "spacex.starlink.user_terminal.status",
     "query": "SELECT \"alert_is_power_save_idle\" FROM \"spacex.starlink.user_terminal.status\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "alert_is_power_save_idle" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "alert_low_motor_current",
     "measurement": "spacex.starlink.user_terminal.status",
     "query": "SELECT \"alert_low_motor_current\" FROM \"spacex.starlink.user_terminal.status\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "alert_low_motor_current" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "alert_lower_signal_than_predicted",
     "measurement": "spacex.starlink.user_terminal.status",
     "query": "SELECT \"alert_lower_signal_than_predicted\" FROM \"spacex.starlink.user_terminal.status\" WHERE $timeFilter",
     "select": [
      [
       {
        "params": [
         "alert_lower_signal_than_predicted"
        ],
        "type": "field"
       }
      ]
     ]
    },
    {
     "alias": "alert_mast_not_near_vertical",
     "measurement": "spacex.starlink.user_terminal.status",
     "query": "SELECT \"alert_mast_not_near_vertical\" FROM \"spacex.starlink.user_terminal.status\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "alert_mast_not_near_vertical" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "alert_motors_stuck",
     "measurement": "spacex.starlink.user_terminal.status",
     "query": "SELECT \"alert_motors_stuck\" FROM \"spacex.starlink.user_terminal.status\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "alert_motors_stuck" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "alert_motors_stuck",
     "measurement": "spacex.starlink.user_terminal.status",
     "query": "SELECT \"alert_motors_stuck\" FROM \"spacex.starlink.user_terminal.status\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "alert_motors_stuck" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "alert_moving_too_fast_for_policy",
     "measurement": "spacex.starlink.user_terminal.status",
     "query": "SELECT \"alert_moving_too_fast_for_policy\" FROM \"spacex.starlink.user_terminal.status\" WHERE $timeFilter",
     "select": [
      [
       {
        "params": [
         "alert_moving_too_fast_for_policy"
        ],
        "type": "field"
       }
      ]
     ]
    },
    {
     "alias": "alert_moving_while_not_mobile",
     "measurement": "spacex.starlink.user_terminal.status",
     "query": "SELECT \"alert_moving_while_not_mobile\" FROM \"spacex.starlink.user_terminal.status\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "alert_moving_while_not_mobile" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "alert_obstruction_map_reset",
     "measurement": "spacex.starlink.user_terminal.status",
     "query": "SELECT \"alert_obstruction_map_reset\" FROM \"spacex.starlink.user_terminal.status\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "alert_obstruction_map_reset" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "alert_power_supply_thermal_throttle",
     "measurement": "spacex.starlink.user_terminal.status",
     "query": "SELECT \"alert_power_supply_thermal_throttle\" FROM \"spacex.starlink.user_terminal.status\" WHERE $timeFilter",
     "select": [
      [
       {
        "params": [
         "alert_power_supply_thermal_throttle"
        ],
        "type": "field"
       }
      ]
     ]
    },
    {
     "alias": "alert_roaming",
     "measurement": "spacex.starlink.user_terminal.status",
     "query": "SELECT \"alert_roaming\" FROM \"spacex.starlink.user_terminal.status\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "alert_roaming" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "alert_slow_ethernet_speeds",
     "measurement": "spacex.starlink.user_terminal.status",
     "query": "SELECT \"alert_slow_ethernet_speeds\" FROM \"spacex.starlink.user_terminal.status\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "alert_slow_ethernet_speeds" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "alert_slow_ethernet_speeds_100",
     "measurement": "spacex.starlink.user_terminal.status",
     "query": "SELECT \"alert_slow_ethernet_speeds_100\" FROM \"spacex.starlink.user_terminal.status\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "alert_slow_ethernet_speeds_100" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "alert_thermal_shutdown",
     "measurement": "spacex.starlink.user_terminal.status",
     "query": "SELECT \"alert_thermal_shutdown\" FROM \"spacex.starlink.user_terminal.status\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "alert_thermal_shutdown" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "alert_thermal_throttle",
     "measurement": "spacex.starlink.user_terminal.status",
     "query": "SELECT \"alert_thermal_throttle\" FROM \"spacex.starlink.user_terminal.status\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "alert_thermal_throttle" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "alert_unexpected_location",
     "measurement": "spacex.starlink.user_terminal.status",
     "query": "SELECT \"alert_unexpected_location\" FROM \"spacex.starlink.user_terminal.status\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "alert_unexpected_location" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Quality stats",
   "type": "state-timeline",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 22 },
   "targets": [
    {
     "alias": "currently_obstructed",
     "measurement": "spacex.starlink.user_terminal.status",
     "query": "SELECT \"currently_obstructed\" FROM \"spacex.starlink.user_terminal.status\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "currently_obstructed" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "is_snr_above_noise_floor",
     "measurement": "spacex.starlink.user_terminal.status",
     "query": "SELECT \"is_snr_above_noise_floor\" FROM \"spacex.starlink.user_terminal.status\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "is_snr_above_noise_floor" ], "type": "field" }
      ]
     ]
    }
   ]
  }
 ]
}