name: Docker Image Build
on:
  push:
  workflow_dispatch:
  release:
    types:
      - created
jobs:
  build:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Tailscale
        uses: tailscale/github-action@v3
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:k8s

      # Docker Buildx を insecure registry 用に設定
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          config-inline: |
            [registry."${{ secrets.DOCKER_GLOBAL_REGISTRY }}"]
              http = true
              insecure = true

      - name: Configure insecure registry
        run: |
          # /etc/docker/daemon.json を直接編集（再起動なし）
          sudo mkdir -p /etc/docker/certs.d/${{ secrets.DOCKER_GLOBAL_REGISTRY }}
          # 空の証明書ファイルを作成して insecure を許可
          sudo touch /etc/docker/certs.d/${{ secrets.DOCKER_GLOBAL_REGISTRY }}/ca.crt

      - name: Manual Docker login (skip TLS)
        run: |
          # curlでinsecureオプション付きでテスト
          curl -k -u "${{ secrets.DOCKER_GLOBAL_USERNAME }}:${{ secrets.DOCKER_GLOBAL_PASSWORD }}" https://${{ secrets.DOCKER_GLOBAL_REGISTRY }}/v2/ && echo "Login test successful"
          # dockerコマンドで直接ログイン
          echo "${{ secrets.DOCKER_GLOBAL_PASSWORD }}" | docker login ${{ secrets.DOCKER_GLOBAL_REGISTRY }} -u "${{ secrets.DOCKER_GLOBAL_USERNAME }}" --password-stdin

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKER_GLOBAL_REGISTRY }}/starlink-grpc-tools:${{ github.event.release.tag_name != '' && github.event.release.tag_name || github.ref_name }}
            ${{ secrets.DOCKER_GLOBAL_REGISTRY }}/starlink-grpc-tools:latest
