name: Docker Image Build
on:
  push:
  workflow_dispatch:
  release:
    types:
      - created
jobs:
  build:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Tailscale
        uses: tailscale/github-action@v3
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:k8s

      # Docker Buildx を insecure registry 用に設定
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          config-inline: |
            [registry."${{ secrets.DOCKER_GLOBAL_REGISTRY }}"]
              http = true
              insecure = true

      - name: Log in to Docker Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.DOCKER_GLOBAL_REGISTRY }}
          username: ${{ secrets.DOCKER_GLOBAL_USERNAME }}
          password: ${{ secrets.DOCKER_GLOBAL_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKER_GLOBAL_REGISTRY }}/starlink-grpc-tools:${{ github.event.release.tag_name != '' && github.event.release.tag_name || github.ref_name }}
            ${{ secrets.DOCKER_GLOBAL_REGISTRY }}/starlink-grpc-tools:latest
