name: Docker Image Build
on:
  push:
  workflow_dispatch:
  release:
    types:
      - created
jobs:
  build:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Tailscale
        uses: tailscale/github-action@v3
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:k8s

      # Docker Buildx をセットアップ
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Configure insecure registry
        run: |
          # Configure Docker daemon to allow insecure registry
          REGISTRY="${{ secrets.DOCKER_GLOBAL_REGISTRY }}"
          echo "{\"insecure-registries\":[\"$REGISTRY\"]}" | sudo tee /etc/docker/daemon.json
          
          # Verify the configuration was written correctly
          cat /etc/docker/daemon.json
          
          # Restart Docker daemon
          sudo systemctl restart docker
          # Wait for Docker to be ready
          sleep 5
          docker info | grep -A5 "Insecure Registries"

      - name: Manual Docker login (skip TLS)
        run: |
          # curlでinsecureオプション付きでテスト
          curl -k -u "${{ secrets.DOCKER_GLOBAL_USERNAME }}:${{ secrets.DOCKER_GLOBAL_PASSWORD }}" https://${{ secrets.DOCKER_GLOBAL_REGISTRY }}/v2/ && echo "Login test successful"
          # dockerコマンドで直接ログイン
          echo "${{ secrets.DOCKER_GLOBAL_PASSWORD }}" | docker login ${{ secrets.DOCKER_GLOBAL_REGISTRY }} -u "${{ secrets.DOCKER_GLOBAL_USERNAME }}" --password-stdin

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKER_GLOBAL_REGISTRY }}/starlink-grpc-tools:${{ github.event.release.tag_name != '' && github.event.release.tag_name || github.ref_name }}
            ${{ secrets.DOCKER_GLOBAL_REGISTRY }}/starlink-grpc-tools:latest
